sudo: required
language: java
jdk: oraclejdk8
services: docker
before_install:
  -docker pull mongo:latest
  -docker run -p 27017:27017
  -npm install -g bower
#after_success:
#-mvn clean test jacoco:report coveralls:report