sudo: required
language: java
jdk: oraclejdk8
services: mongodb
before_install:
  - npm install -g bower
  - mvn -N io.takari:maven:wrapper
after_success:
  - mvn clean test -Ptest jacoco:report coveralls:report
