sudo: required
language: java
jdk: oraclejdk8
services: neo4j
before_install:
  - npm install -g bower
  - mvn -N io.takari:maven:wrapper
after_success:
  - mvn clean test jacoco:report coveralls:report
